server:
  port: 8762
spring:
  application:
    name: server-client
#    客户端每隔5分钟向注册中心发送一次心跳
eureka:
  client:
    serviceUrl:
      defaultZone: http://peer1:8761/eureka/,http://peer2:8769/eureka/
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream